### ISSUE TITLE
Vorstellung Automatisierung für Email-Benachrichtigung wenn Aschekasten voll wird

### ISSUE THREAD

**Issue by iamthe1st** [TheRealKillaruna/nano_pk#36]
Hallo zusammen,
ich möchte hier kurz meine Automatisierung vorstellen.
Mein Aschekasten ist immer wenn etwa 300kg Pellets verbrannt wurden nahzu voll, da sich das je nach Wetter ändert lasse ich mir automatisch eine Email schicken und muss den Aschekasten nicht mehr kontrollieren:

Configurations.yaml:

```
  - sensor:
      - name: "FuellstandAschekasten"
        unit_of_measurement: "%"
        state: > 
         {{ ((1- (states('input_number.letzteascheleerung')|int - states('sensor.nano_pk_verbrauchszaehler')|int)/330)*100)|round(1)  }}
```

```
input_number:
  letzteascheleerung:
    name: letzteAscheLeerung
    min: 0
    max: 50000
    step: 1
    mode: box
    icon: mdi:weightkilogram

```

```
notify:
  - name: "Email_Hinweis"
    platform: smtp
    server: "smtp.web.de"
    port: 587
    timeout: 15
    sender: "absender@web.de"
    encryption: starttls
    username: "BENUTZERNAME"
    password: "GeheimesPasswort"
    recipient:
      - "DeineEmailAdresse@gmail.com"
    sender_name: "Home Assistant"
```

automationy.yaml:

```
- id: '29071238'
  alias: AscheKastenVoll
  trigger:
  - platform: template
    value_template: '{{ (states(''sensor.nano_pk_verbrauchszaehler'')|int ) > (states(''input_number.letzteascheleerung'')|int
      )  }}'
  action:
  - service: persistent_notification.create
    data:
      message: Asche Kasten fast voll
  - service: notify.Email_Hinweis
    data:
      message: 'Asche Kasten fast voll. '
      title: Asche Kasten fast voll
  - service: input_number.set_value
    target:
      entity_id: input_number.letzteascheleerung
    data:
      value: '{{ states(''sensor.nano_pk_verbrauchszaehler'')|float(0) + 330 }}'

```

Ich hoffe der Code hilft euch weiter.
